USE UEFA;

-- Business scenario Q121 - Team with Most Away Wins
SELECT TOP 1 T.TEAM_NAME AS TeamName
	, COUNT(*) AS AwayWins
FROM UCL.Matches M
INNER JOIN UCL.Teams T ON M.HOME_TEAM_ID = T.TEAM_ID OR M.AWAY_TEAM_ID = T.TEAM_ID
WHERE M.SEASON = '2021-2022' AND M.AWAY_TEAM_SCORE > M.HOME_TEAM_SCORE
GROUP BY T.TEAM_NAME
ORDER BY COUNT(*) DESC
;



-- Business scenario Q122 - Stadium with Most Matches
SELECT TOP 1 S.NAME AS StadiumName
	, S.CITY AS City
	, COUNT(M.MATCH_ID) AS MatchesCount
FROM UCL.Matches M
INNER JOIN UCL.Stadiums S ON M.STADIUM = S.NAME
WHERE M.SEASON = '2021-2022'
GROUP BY S.NAME, S.CITY
ORDER BY COUNT(M.MATCH_ID) DESC
;



-- Business scenario Q123 - Stadiums by Country
SELECT S.COUNTRY AS Country
	, COUNT(S.STADIUM_ID) AS StadiumCount
FROM UCL.Stadiums S
GROUP BY S.COUNTRY
ORDER BY COUNT(S.STADIUM_ID) DESC
;



-- Business scenario Q124 - Most Experienced Players
SELECT TOP 3 CONCAT(P.FIRST_NAME, ' ', P.LAST_NAME) AS PlayerFullName
	, P.DOB AS DateOfBirth
	, P.NATIONALITY AS Nationality
	, T.TEAM_NAME AS Team
FROM UCL.Players P
INNER JOIN UCL.Teams T ON P.TEAM = T.TEAM_ID
WHERE P.DOB IS NOT NULL
ORDER BY P.DOB
;



-- Business scenario Q125 - Team with Widest Goal Margin Victory
SELECT TOP 1 T.TEAM_NAME AS Team
	, M.HOME_TEAM_SCORE AS HomeScore
	, M.AWAY_TEAM_SCORE AS AwayScore
	, ABS(M.HOME_TEAM_SCORE - M.AWAY_TEAM_SCORE) AS GoalMargrin
FROM UCL.Matches M
INNER JOIN UCL.Teams T ON (M.HOME_TEAM_ID = T.TEAM_ID AND M.HOME_TEAM_SCORE > M.AWAY_TEAM_SCORE)
	OR (M.AWAY_TEAM_ID = T.TEAM_ID AND M.AWAY_TEAM_SCORE > M.HOME_TEAM_SCORE)
ORDER BY ABS(M.HOME_TEAM_SCORE - M.AWAY_TEAM_SCORE) DESC
;